import type { Metadata } from "next";
import "bootstrap-icons/font/bootstrap-icons.min.css"
import "@/styles/custom.scss"
import"@/styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <h1 className="bg-blue">Hola mundo</h1>
        {children}
      </body>
    </html>
  );
}
